name: bumblebee_test
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.3.1
  - alsa-lib=1.2.14
  - aom=3.9.1
  - autoconf=2.72
  - automake=1.17
  - bazel=6.5.0
  - binutils_impl_linux-64=2.44
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - clang=15.0.7
  - clang-15=15.0.7
  - clangxx=15.0.7
  - cmake=3.24.3
  - contourpy=1.3.2
  - curl=8.17.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - freetype=2.14.1
  - gcc=11.4.0
  - gcc_impl_linux-64=11.4.0
  - giflib=5.2.2
  - graphite2=1.3.14
  - gxx=11.4.0
  - gxx_impl_linux-64=11.4.0
  - harfbuzz=11.4.5
  - humanize=4.14.0
  - icu=75.1
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp15=15.0.7
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=11.4.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.3
  - libgomp=15.2.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsanitizer=11.4.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=11.4.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libtool=2.5.4
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - m4=1.4.20
  - make=4.4.1
  - markdown-it-py=4.0.0
  - matplotlib-base=3.10.8
  - mdurl=0.1.2
  - ml_dtypes=0.5.4
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - nasm=2.16.03
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - ninja=1.13.2
  - numpy=1.26.4
  - openjdk=11.0.27
  - openjpeg=2.5.4
  - openssl=3.6.0
  - opt-einsum=3.4.0
  - opt_einsum=3.4.0
  - packaging=25.0
  - pcre2=10.45
  - perl=5.32.1
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pybind11-abi=11
  - pygments=2.19.2
  - pyparsing=3.2.5
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyyaml=6.0.3
  - qhull=2020.2
  - rav1e=0.7.1
  - re2=2025.11.05
  - readline=8.3
  - rhash=1.4.3
  - rich=14.2.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - svt-av1=3.1.2
  - sysroot_linux-64=2.34
  - tk=8.6.15
  - toolz=1.1.0
  - treescope=0.1.10
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - unicodedata2=17.0.0
  - unzip=6.0
  - wget=1.25.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chex==0.1.82
      - cloudpickle==3.1.2
      - datasets==2.14.6
      - dill==0.3.7
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - flax==0.7.4
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.66.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.17.3
      - idna==3.11
      - jax==0.4.13
      - jaxlib==0.4.13
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.15
      - namex==0.1.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - optax==0.2.1
      - optree==0.18.0
      - orbax==0.1.9
      - orbax-checkpoint==0.5.16
      - pandas==2.3.3
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==14.0.2
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.5.2
      - scipy==1.15.3
      - sympy==1.14.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-cpu==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.78
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.13.3
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.31.0
      - triton==3.5.1
      - tzdata==2025.2
      - urllib3==2.6.2
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix:
