name: bumblebee_test
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - autoconf=2.72=pl5321hbb4ee43_1
  - automake=1.17=pl5321ha770c72_0
  - bazel=6.5.0=h2a8fbb5_5
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - clang=15.0.7=h39da44c_5
  - clang-15=15.0.7=default_h127d8a8_5
  - clangxx=15.0.7=default_h127d8a8_5
  - cmake=3.24.3=h816a3e0_0
  - contourpy=1.3.2=py310h3788b33_0
  - curl=8.17.0=h4e3cde8_0
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hd590300_0
  - expat=2.7.3=h7354ed3_3
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - gcc=11.4.0=h602e360_13
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=hecca717_2
  - gxx=11.4.0=h602e360_13
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - harfbuzz=11.4.5=h15599e2_0
  - humanize=4.14.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=4_h0358290_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=h7354ed3_3
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.84.3=hf39c6af_0
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=4_h47877c9_openblas
  - libllvm15=15.0.7=ha7bfdaf_5
  - libltdl=2.4.3a=h5888daf_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsanitizer=11.4.0=h5763a12_13
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h9d88235_1
  - libtool=2.5.4=h5888daf_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - m4=1.4.20=hb9d3cd8_0
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ml_dtypes=0.5.4=np2py310h3d4ba91_0
  - msgpack-python=1.1.2=py310h03d9f68_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nasm=2.16.03=h4bc722e_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - ninja=1.13.2=h171cf75_0
  - numpy=1.26.4=py310hb13e2d6_0
  - openjdk=11.0.27=h5ddf6bc_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=12.0.0=py310h5a73078_2
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=11=hc364b38_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - rhash=1.4.3=hd590300_2
  - rich=14.2.0=pyhcf101f3_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.0=h2a70700_0
  - svt-av1=3.1.2=hecca717_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.15=h54e0aa7_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - treescope=0.1.10=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - unzip=6.0=hb03c661_4
  - wget=1.25.0=hc2d8bac_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.3.2=h54a6638_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chex==0.1.82
      - cloudpickle==3.1.2
      - datasets==2.14.6
      - dill==0.3.7
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - flax==0.7.4
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.66.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.17.3
      - idna==3.11
      - jax==0.4.13
      - jaxlib==0.4.13
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.15
      - namex==0.1.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - optax==0.2.1
      - optree==0.18.0
      - orbax==0.1.9
      - orbax-checkpoint==0.5.16
      - pandas==2.3.3
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==14.0.2
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.5.2
      - scipy==1.15.3
      - sympy==1.14.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-cpu==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.78
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.13.3
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.31.0
      - triton==3.5.1
      - tzdata==2025.2
      - urllib3==2.6.2
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: 
